select * from customer;

-- what is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as total_revenue
from customer
group by gender;

--which customers used a discount but still spent more than avg purchase amt?
select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=
(select avg(purchase_amount) 
from customer);

--which are the top 5 products with the highest avg ratings?
select item_purchased,round(avg(review_rating)::numeric,2) as avg_ratings
from customer
group by item_purchased
order by avg_ratings desc
limit 5;

--compare the avg purchase amt between standard and express shipping?
select shipping_type,round(avg(purchase_amount)::numeric,2) as avg_purchase
from customer
where shipping_type in ('Standard','Express')
group by shipping_type
order by avg_purchase desc;


--Do subscribed customers spent more? compare avg spent and total revenue btw sub and non-sub?
select subscription_status,count(customer_id) as total_customer,
round(avg(purchase_amount)::numeric,2) as avg_purchase,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by  total_revenue,avg_purchase desc;

--which 5 product have the highest percentage of purchases with discount applied?
select item_purchased,
       ROUND(100.0 * SUM(CASE WHEN LOWER(discount_applied) = 'yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
from customer
group by  item_purchased
order by  discount_rate DESC
limit 5;

--segment customers into new,returning and loyal based on their total num of previous purchases
-- and show the count of each segment?
with customer_type as (
select customer_id,previous_purchases,
case
when previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'returning'
else 'loyal' 
end as customer_segment
from customer
)

select customer_segment,count(*) as no_of_customers
from customer_type
group by customer_segment 
order by no_of_customers desc;

--what are top 3 most purchased products within each category?
with item_counts as (
select category,item_purchased,count(customer_id) as total_order,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)

select item_rank,category,item_purchased,total_order
from item_counts
where item_rank<=3;

--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status
order by repeat_buyers desc;

--what is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;







